name = "super-frost-d434"
main = "main-website-worker.js"
compatibility_date = "2025-06-01"

[[routes]]
pattern = "realitymechanics.nz"
custom_domain = true

[[d1_databases]]
binding = "ATLAS_DB"
database_name = "atlas-d1"
database_id = "ffc9622e-02a4-4561-b11e-4e54fac92967"
